server:
  servlet:
    context-path: /boot
  port: 8081


#book:
  #name: Spring
  #writer: hugx
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT%2b8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
  jpa:
    database: mysql
    show-sql: true